using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudyHub.Web.Data.Entities;

/// <summary>
/// Represents a registered student/user in the StudyHub platform.
/// Extends the base ASP.NET Core IdentityUser.
/// </summary>
public class ApplicationUser : IdentityUser
{
    public string FirstName { get; set; } = string.Empty;

    public string LastName { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation Properties

    /// <summary>
    /// The study groups this user is a member of.
    /// </summary>
    public virtual ICollection<GroupMember> GroupMemberships { get; set; } = new List<GroupMember>();

    /// <summary>
    /// The resources (files/links) this user has uploaded across all groups.
    /// </summary>
    public virtual ICollection<Resource> UploadedResources { get; set; } = new List<Resource>();

    /// <summary>
    /// The activity feed events generated by this user.
    /// </summary>
    public virtual ICollection<ActivityFeed> ActivityFeeds { get; set; } = new List<ActivityFeed>();

    /// <summary>
    /// The system notifications and alerts sent to this user.
    /// </summary>
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    /// <summary>
    /// Invitations this user has received to join other study groups.
    /// </summary>
    [InverseProperty(nameof(GroupInvitation.Invitee))]
    public virtual ICollection<GroupInvitation> ReceivedInvitations { get; set; } = new List<GroupInvitation>();

    /// <summary>
    /// Invitations this user has sent out as a Group Admin.
    /// </summary>
    [InverseProperty(nameof(GroupInvitation.Inviter))]
    public virtual ICollection<GroupInvitation> SentInvitations { get; set; } = new List<GroupInvitation>();
}